### PR TITLE
Fix fmt include dirs

### PR DESCRIPTION
**Pull request by davidrohr**
This fixes the problem with the input directories, that was also pointed out by @sy-c before.
The problem is not between the `find_package(fmt)` and the version from the FairLogger manual.
Instead, the problem is that Readout is not using modern CMake targets, thus the dependencies from FairLogger are not propagated.
This PR fixes that. Just as a remark, for the future one could check if the CMake could be modernized to use FairMQ::FairMQ directly as target, which will get us rid of these workarounds.

Anyhow, with this PR it works for me in the CI container.
Could you create another tag with it? :)

### CODE REVIEW

**Comment by sy-c** [comment]
The problem does not come from readout, it comes from the FairLogger::FairLogger target which does not expose correctly its compile time dependencies in the target INTERFACE_INCLUDE_DIRECTORIES.

Readout does use modern cmake and use only targets, not exported variables. It extracts from the targets the compile time includes in some local vars needed to build object modules.

If the FMQ cmake was done properly, the only thing a cmake file using fmq lib should care about is fmq::fmq
and not having to add manually (and maintain) boost, fairlogger, fmt, and whatever else they are going to add in the future.

**Comment by sy-c** [comment]
@davidrohr Readout v1.4.2 has been tagged,
cheers

**Comment by davidrohr** [comment]
Hm, weird, you seem indeed to link to FairMQ::FairMQ. Perhaps the problem is with FairMQ. Since I think FairLogger::FairLogger would pull in fmt::fmt correctly.
Anyway, I am not that much a CMake expert, and I am also not responsible for FairMQ.
Thanks for merging, hope this will be enough for us for now :)

**Comment by sy-c** [comment]
thanks to you for the fix! have a nice week-end :)

**Pull request merged**
