### PR TITLE
Adapt to FairMQ v1.4.2+

### PR DESCRIPTION
**Pull request by dennisklein**
You do not need to take this code necessarily, so FYI: this should be the minimum changes needed to adapt to the changes in the state machine in FairMQ `v1.4.2+`. This PR is not backwards compatible.

### CODE REVIEW

**Comment by dennisklein** [comment]
aliBuild support for the -DBUILD_OFI_TRANSPORT=ON FairMQ build flag is proposed in AliceO2Group/alidist#1557.

**Comment by awegrzyn** [comment]
This is necessary for https://github.com/alisw/alidist/pull/1557

**Comment by awegrzyn** [comment]
@sy-c Would it me possible to have a separate branch with this patch so I could test it easily against new alidist recipes?

**Comment by awegrzyn** [comment]
@sy-c Can I now merge that I tag a new version?

**Comment by awegrzyn** [comment]
I'm merging as it does not break current setup

**Pull request merged**
