### PR TITLE
Fixes for build on mac

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
is it a problem ?

**Comment by sy-c** [comment]
I will modify the cmake and source code with a proper switch when not found. Latest version of readout.exe is also needing it. We can't just drop both executables.

**Comment by Barthelemy** [comment]
ok great, thanks

**Comment by sy-c** [comment]
Numa support has been made optional in #9 with a proper FindNuma.cmake

**Comment by Barthelemy** [comment]
Could we get a new release of Readout with this fix ?

**Comment by sy-c** [comment]
v0.5.0 has been tagged

**Comment by Barthelemy** [comment]
ok it works
can I bump in alidist ?

**Pull request closed without merging**
