### PR TITLE
Add fmt dependency (required by FairLogger)

### PR DESCRIPTION
**Pull request by davidrohr**
This is required by FairLogger. They intentionally do not find dependencies themselves in their CMakeTargets and do not pass them over as public interface library, so we have to add it ourselves.

If this OK for you, could you create a new tag with this.
I need this to bump FairLogger.

### CODE REVIEW

**Comment by davidrohr** [comment]
Sure, that sounds reasonable. Shall I update this one?

**Comment by sy-c** [comment]
No need, I'll commit directly in my branch so that I can test it and release a new tag quickly. I'll close this one when this is done.

**Comment by sy-c** [comment]
I don't have the impression that the magic for loop is working, so I kept this one for the time being.

**Comment by davidrohr** [comment]
Ah, wait, sorry, I had already updated this with the one from the FairLogger manual.

**Comment by sy-c** [comment]
oops, sorry I did not checked... I have tagged readout v1.4.1 with this change. Do you want to try it first or should I tag v1.4.2 with the simple "find_package(fmt)" ? I'm actually not sure to check how it works...

**Comment by davidrohr** [comment]
Let me check it, if it doesn't work we have to create yet another one. But actually, if it doesn't work it is a problem with FairLogger and should be fixed there :)

**Comment by davidrohr** [comment]
1.4.1 works for me, so seems OK, I'll open a PR to alidist later and bump all required packages for the new FairLogger. Then let's see what the CI says.

**Pull request merged**
