### PR TITLE
Fix possible string truncation, that triggers compiler warning

### PR DESCRIPTION
**Pull request by davidrohr**
@sy-c : Could you merge this and create yet another tag?
Sorry for the mess. I have tested in the CI container locally that this is the last fix that is needed at least :)

### CODE REVIEW

**Comment by sy-c** [comment]
Hello @davidrohr ,
what exotic compiler version/options are used to generate this warning? The existing code looks perfectly safe and valid to me.

**Comment by davidrohr** [comment]
CC8 GCC 8.3 with -Werror=format-truncation
Actually the error is not about out of bounds but about possible string truncation, you are right :)

**Comment by ktf** [comment]
BTW, I understand why we suddenly have `-Werror` triggering for Readout. This was actually introduced ages ago in https://github.com/alisw/alidist/pull/1754, however it never actually ran because all the CI environments where Readout was present were not defining ALIBUILD_RUN_TESTS. This changed recently with the introduction of the fullO2 test and the fact we run tests there, triggering the breakage.

**Comment by sy-c** [comment]
ok, done
https://github.com/alisw/alidist/pull/2649

**Pull request merged**
