### PR TITLE
Fix missing return value

### PR DESCRIPTION
**Pull request by davidrohr**
Could you create a tag with this fix? Current version 1.4.7 breaks the GPU CI.

### CODE REVIEW

**Comment by sy-c** [comment]
This is fixed here:
https://github.com/AliceO2Group/Readout/tree/v1.4.7.1

and alidist bump PR here:
https://github.com/alisw/alidist/pull/2511

(can not use the master branch for this fix, which already includes some other breaking changes vs 1.4.7).

Out of curiosity, what does readout has to do with GPU CI ?

**Comment by sy-c** [comment]
(and thanks for reporting ! I also came on this while doing some other warning checks)

**Comment by davidrohr** [comment]
@sy-c : The GPU CI is in some sense the "full" CI, it tests CC8 + GPU + CodeChecker + full O2Suite build.
I already suggested that we should rename it, will suggest again.

**Comment by sy-c** [comment]
Understood... I indeed have not run readout on CC8 so far, but will make further checks for next readout releases. thanks!

**Pull request closed without merging**
